### ISSUE TITLE
cannot execute koadic 

### ISSUE THREAD

**Issue by bassem97** [offsecginger/koadic#3]
After cloning the project and installing requirements when running koadic it throw this import error !

```
Traceback (most recent call last):
  File "/home/bassem/Desktop/koadic/./koadic", line 178, in <module>
    shell = core.shell.Shell(banner, __version__)
  File "/home/bassem/Desktop/koadic/core/shell.py", line 18, in __init__
    self.plugins = core.loader.load_plugins("modules", True, self)
  File "/home/bassem/Desktop/koadic/core/loader.py", line 36, in load_plugins
    env = __import__(file, )
  File "/home/bassem/Desktop/koadic/modules/implant/inject/mimikatz_dotnet2js.py", line 3, in <module>
    import core.cred_parser
  File "/home/bassem/Desktop/koadic/core/cred_parser.py", line 2, in <module>
    import tabulate
  File "/usr/lib/python3/dist-packages/tabulate.py", line 16, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

**Comment by offsecginger** [comment]
This is an issue in python 3.10. I'm not exactly sure what the remedy is
for it other than using 3.9

**Comment by bassem97** [comment]
Its weird 🥺
